### ISSUE TITLE
Peer to Peer code review 

### ISSUE THREAD

**Issue by Nizamuddin4493** [karam084/online-course#2]
Please make changes as described below
-
- I would suggest you remove all commented codes from your site.
- Kindly display properly the images and it would be better to give it margin from both sides.
- Kindly set the buttons, because they are over the images In the Main Program section.
- Kindly use proper margins between the elements in the Partner section.

**Comment by karam084** [comment]
Solved Thank you

**Comment by karam084** [comment]
Solved
